# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    adapter: postgresql
    database: MovieMakers_development
  users:
    adapter: postgresql
    database: DataLionNav_development
    migrations_paths: db/users_migrate
  users_read:
    adapter: postgresql
    database: DataLionNav_development
    replica: true

production:
  primary:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  users:
    adapter: postgresql
    url: <%= ENV['USER_DB_URL'] %>
    migrations_paths: db/users_migrate
